server:
  port: 8080
spring:
  application:
    name: modbus-svr
modbus:
  master:
    global:
      address:
        - 192.168.1.88:502
      maxTotal: 1
      maxIdle: 1
      maxWaitMillis: 1000
      slaveId: 1
      startAddress: 0
      registerNumber: 8
  device:
    bit: 4,4,4,4,4,4,4,4
    digit: 1,1,1,1,1,1,1,1
    num: 1,2,3,4,5,6,7,8
    proType: 3000,3001,5003,5004,5010,5030,5033,5099
    dealWay: SIMPLE,SIMPLE,SIMPLE,SIMPLE,SIMPLE,SIMPLE,SIMPLE,SIMPLE
